### ISSUE TITLE
Would it be possible to add an option to view all the tags that user has?

### ISSUE THREAD

**Issue by nikitavoloboev** [fniephaus/alfred-pocket#26]
I want to have one more option in this main window : 

![2016-07-15 at 13 16](https://cloud.githubusercontent.com/assets/6391776/16872625/4ea7f666-4a8e-11e6-993f-6bbda20de7dd.png)

Which would be 'my tags' and from there I can search and see the various tags that I have. On clicking the tags, I would be able to see the articles associated with the tags.

This would really be amazing to have. I hope you agree and I hope it won't be too complex to implement.

Thank you.

**Comment by fniephaus** [comment]
Thanks for the suggestion. I might add the feature when I have some time, but I'm currently quite busy I'm afraid.

**Comment by Meflou** [comment]
It would be amazing if that will be done. Also when adding a new link, it is good if it can display tags for the user to choose from instead of typing them manually.
<img width="634" alt="komypp2" src="https://cloud.githubusercontent.com/assets/10213346/17213276/5f7e1e0e-54dc-11e6-8614-2d84d99c8a18.png">

**Comment by fniephaus** [comment]
I might have some time to do this in the next few weeks...
